hmpps.sqs:
  provider: localstack
  queues:
    audit:
      queueName: ${random.uuid}
    updatefromexternalsystemevents:
      queueName: update_from_external_system_events_queue
      dlqName: update_from_external_system_events_dlq
  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}
