server:
  shutdown: immediate

api:
  base:
    url:
      oauth: http://localhost:9090/auth
      prisoner-search: http://localhost:8083
      prison-register: http://localhost:8084
      prison-api: http://localhost:8085

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

spring:
  devtools:
    add-properties: true

  datasource:
    url: jdbc:postgresql://localhost:5432/locations_inside_prison?sslmode=prefer
    username: locations_inside_prison
    password: locations_inside_prison

  jpa:
    show-sql: true