environment:
  name: undefined

generic-service:
  nameOverride: hmpps-locations-inside-prison-api
  productId: "DPS039"

  serviceAccountName: hmpps-locations-inside-prison-api

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-locations-inside-prison-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: locations-inside-prison-api-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_SQS_USE_WEB_TOKEN: "true"
    SERVICE_RESIDENTIAL_ACTIVATED_PER_PRISON: true

  envFrom:
    - secretRef:
        name: hmpps-locations-inside-prison-api

  namespace_secrets:
    dps-rds-instance-output:
      DATABASE_ENDPOINT: "rds_instance_endpoint"
      DATABASE_NAME: "database_name"
      DATABASE_USERNAME: "database_username"
      DATABASE_PASSWORD: "database_password"
      SPRING_FLYWAY_USER: "database_username"
      SPRING_FLYWAY_PASSWORD: "database_password"

  allowlist:
    groups:
      - internal

  modsecurity_enabled: true
  modsecurity_snippet: |
    SecRuleEngine DetectionOnly
    SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
    SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
    SecAction "id:900000,phase:1,nolog,pass,t:none,setvar:tx.paranoia_level=2"

generic-prometheus-alerts:
  targetApplication: hmpps-locations-inside-prison-api
  alertSeverity: move-a-prisoner-alerts-nonprod
