---
# Per environment values which override defaults in hmpps-locations-inside-prison-api/values.yaml

generic-service:
  ingress:
    host: locations-inside-prison-api.hmpps.service.justice.gov.uk

  env:
    JAVA_OPTS: "-Xmx1539m"
    API_BASE_URL_OAUTH: https://sign-in.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_PRISONER_SEARCH: https://prisoner-search.prison.service.justice.gov.uk
    API_BASE_URL_PRISON_REGISTER: https://prison-register.hmpps.service.justice.gov.uk
    API_BASE_URL_PRISON_API: https://prison-api-dev.prison.service.justice.gov.uk
    SERVICE_ACTIVE_PRISONS: ""

  namespace_secrets:
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_DOMAINEVENTS_ARN: "topic_arn"
    sqs-hmpps-audit-secret:
      HMPPS_SQS_QUEUES_AUDIT_QUEUE_NAME: "sqs_queue_name"
    sqs-prisoner-event-queue-secret:
      HMPPS_SQS_QUEUES_LOCATIONSINSIDEPRISON_QUEUE_NAME: "sqs_queue_name"
    sqs-prisoner-event-queue-dlq-secret:
      HMPPS_SQS_QUEUES_LOCATIONSINSIDEPRISON_DLQ_NAME: "sqs_queue_name"

  postgresDatabaseRestore:
    enabled: true
    namespace_secrets:
      dps-rds-instance-output:
        DB_NAME: "database_name"
        DB_USER: "database_username"
        DB_PASS: "database_password"
        DB_HOST: "rds_instance_address"
      dps-rds-instance-output-preprod:
        DB_NAME_PREPROD: "database_name"
        DB_USER_PREPROD: "database_username"
        DB_PASS_PREPROD: "database_password"
        DB_HOST_PREPROD: "rds_instance_address"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-prisoner-cell-allocation-prod
  rdsAlertsDatabases:
    cloud-platform-a2d6489b50a08faa: locations-inside-prison-api
  sqsAlertsQueueNames:
    - locations-inside-prison-production-prisoner-event-queue
    - locations-inside-prison-production-prisoner-event-dlq