---
# Per environment values which override defaults in hmpps-locations-inside-prison-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: locations-inside-prison-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth

  scheduledDowntime:
    enabled: true
    startup: '49 6 * * 1-5' # Start at 6.49am UTC Monday-Friday
    shutdown: '58 21 * * 1-5' # Stop at 9.58pm UTC Monday-Friday

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: digital-prison-service-dev
  rdsAlertsDatabases:
    cloud-platform-354c58598c277a2a: locations-inside-prison-api
  sqsAlertsQueueNames:
    - locations-inside-prison-preprod-prisoner-event-queue
    - locations-inside-prison-preprod-prisoner-event-dlq