---
# Per environment values which override defaults in hmpps-locations-inside-prison-api/values.yaml
environment:
  name: preprod

generic-service:
  replicaCount: 2

  ingress:
    host: locations-inside-prison-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_PRISONER_SEARCH: https://prisoner-search-preprod.prison.service.justice.gov.uk
    API_BASE_URL_PRISON_REGISTER: https://prison-register-preprod.hmpps.service.justice.gov.uk
    API_BASE_URL_PRISON_API: https://prison-api-preprod.prison.service.justice.gov.uk
    API_BASE_URL_MANAGE_USERS: https://manage-users-api-preprod.hmpps.service.justice.gov.uk

  namespace_secrets:
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_DOMAINEVENTS_ARN: "topic_arn"
    sqs-hmpps-audit-secret:
      HMPPS_SQS_QUEUES_AUDIT_QUEUE_NAME: "sqs_queue_name"
    sqs-prisoner-event-queue-secret:
      HMPPS_SQS_QUEUES_LOCATIONSINSIDEPRISON_QUEUE_NAME: "sqs_queue_name"
    sqs-prisoner-event-queue-dlq-secret:
      HMPPS_SQS_QUEUES_LOCATIONSINSIDEPRISON_DLQ_NAME: "sqs_queue_name"

  scheduledDowntime:
    enabled: true
    startup: '49 6 * * 1-5' # Start at 6.49am UTC Monday-Friday
    shutdown: '58 21 * * 1-5' # Stop at 9.58pm UTC Monday-Friday

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  businessHoursOnly: true
  rdsAlertsDatabases:
    cloud-platform-354c58598c277a2a: locations-inside-prison-api
  sqsAlertsQueueNames:
    - locations-inside-prison-preprod-prisoner-event-queue
    - locations-inside-prison-preprod-prisoner-event-dlq