-- Data dictionary for the locations inside prison schema.
--
-- These comments are read by SchemaSpy (published to GitHub Pages) and by anything else that reads
-- pg_description, including the CSV export for the MOJ Data Catalogue / Glue. Keep them updated when
-- columns are added or their meaning changes - SchemaCommentsTest fails the build if a table or column
-- has no comment.
--
-- Every column comment ends with a sensitivity classification:
--
--   [Sensitivity: NONE]                - not personal data in itself (keys, timestamps, process flags,
--                                        and capacity figures MoJ already publishes)
--   [Sensitivity: PERSONAL]            - personal data about a prisoner: identifies or locates them
--   [Sensitivity: STAFF]               - personal data about a member of staff, typically the username
--                                        that performed an action
--   [Sensitivity: SPECIAL-CATEGORY]    - UK GDPR Article 9 data (health, sexuality, religion, race,
--                                        gender reassignment) or criminal offence data under Article 10
--   [Sensitivity: OFFICIAL-SENSITIVE]  - not personal data, but damaging if disclosed
--
-- STAFF is still personal data and still in scope for a staff member's own subject access request. It is
-- separated from PERSONAL so that an extract about prisoners can be reasoned about without staff columns
-- inflating the count, and so staff data can be dropped or pseudonymised independently.
--
-- Three things to understand before using these classifications:
--
--   1. They describe the column's own content, not the row's. This schema describes the physical estate,
--      not people, so almost nothing here is about a prisoner - which is exactly why the handful of
--      columns that can name one matter.
--
--   2. **Capacity figures are split.** Figures MoJ already publishes - a prison's signed operational
--      capacity, and the certified capacity of a location as built - are NONE. Figures that are proposed
--      but not yet approved are OFFICIAL-SENSITIVE: they reveal intended changes to the estate ahead of
--      any announcement. That is the difference between certification_approval_request (a request) and
--      cell_certificate (the approved outcome).
--
--   3. **Every free-text column should be assumed to contain more than its question asks.** A field
--      asking why a cell was deactivated is routinely used to record which prisoner damaged it. Free
--      text is classified on what people actually write in it, not on the field label.
--
-- Audit columns recur across most tables and carry the same meaning everywhere:
--   when_created / when_updated  - when the row was first written / last changed          [NONE]
--   updated_by / amended_by      - DPS username of the person who made the change         [STAFF]


-- ---------------------------------------------------------------------------------------------------
-- location and its satellites
-- ---------------------------------------------------------------------------------------------------

COMMENT ON TABLE location IS 'Every location inside a prison, from a wing down to an individual cell, held as a self-referencing tree via parent_id. Single-table inheritance: location_type_discriminator says which kind of location a row is, and which columns are meaningful.';
COMMENT ON COLUMN location.id IS 'Primary key. A UUIDv7 generated by the application, used as the location''s permanent public identifier across DPS. [Sensitivity: NONE]';
COMMENT ON COLUMN location.prison_id IS 'Prison the location belongs to, as a NOMIS agency code such as MDI. [Sensitivity: NONE]';
COMMENT ON COLUMN location.path_hierarchy IS 'Full path of the location within the prison, hyphen separated, such as A-1-001. Unique within a prison and used with prison_id to form the location key. [Sensitivity: NONE]';
COMMENT ON COLUMN location.code IS 'The location''s own code within its parent, such as 001 for cell A-1-001. Not unique on its own. [Sensitivity: NONE]';
COMMENT ON COLUMN location.location_type IS 'What kind of location this is - WING, LANDING, CELL, ADJUDICATION_ROOM and so on. See LocationType in reference-data.csv. [Sensitivity: NONE]';
COMMENT ON COLUMN location.parent_id IS 'The location immediately above this one in the tree. Null for a top level location such as a wing. [Sensitivity: NONE]';
COMMENT ON COLUMN location.local_name IS 'Name the prison uses for this location in conversation, such as "Houseblock 1". Optional; the path hierarchy is the authoritative identifier. [Sensitivity: NONE]';
COMMENT ON COLUMN location.comments IS 'Free text notes about the location. Free text: assume it can name a prisoner, for example when explaining why a cell is out of use. [Sensitivity: PERSONAL]';
COMMENT ON COLUMN location.order_within_parent_location IS 'Sort order among siblings, so a wing''s landings list in the order staff expect rather than alphabetically. [Sensitivity: NONE]';
COMMENT ON COLUMN location.residential_housing_type IS 'Legacy NOMIS housing classification, superseded by accommodation_type. Retained because historic rows and the NOMIS sync still carry it. See ResidentialHousingType in reference-data.csv. [Sensitivity: NONE]';
COMMENT ON COLUMN location.capacity_id IS 'Foreign key to capacity, holding this location''s working capacity, maximum capacity and certified normal accommodation. Null for locations that hold no one. [Sensitivity: NONE]';
COMMENT ON COLUMN location.deactivated_date IS 'When the location was taken out of use. Null while it is in use. [Sensitivity: NONE]';
COMMENT ON COLUMN location.deactivated_reason IS 'Why the location was taken out of use - DAMAGED, MAINTENANCE, REFURBISHMENT and so on. See DeactivatedReason in reference-data.csv. [Sensitivity: NONE]';
COMMENT ON COLUMN location.proposed_reactivation_date IS 'Date the prison expects the location to come back into use. An estimate, not a commitment. [Sensitivity: NONE]';
COMMENT ON COLUMN location.when_created IS 'When this location record was first created. [Sensitivity: NONE]';
COMMENT ON COLUMN location.when_updated IS 'When this location record was last changed. [Sensitivity: NONE]';
COMMENT ON COLUMN location.updated_by IS 'DPS username of the last person to change this location. [Sensitivity: STAFF]';
COMMENT ON COLUMN location.accommodation_type IS 'What the location is used for at the top level - NORMAL_ACCOMMODATION, HEALTHCARE_INPATIENTS, CARE_AND_SEPARATION or OTHER_NON_RESIDENTIAL. Drives roll count reporting. See AccommodationType in reference-data.csv. [Sensitivity: NONE]';
COMMENT ON COLUMN location.planet_fm_reference IS 'Reference for the corresponding job in Planet FM, the facilities management system, when a location is out of use for maintenance. [Sensitivity: NONE]';
COMMENT ON COLUMN location.converted_cell_type IS 'What a former cell is now used as, when it has been converted to a non-residential room - OFFICE, STORE, SHOWER and so on. See ConvertedCellType in reference-data.csv. [Sensitivity: NONE]';
COMMENT ON COLUMN location.other_converted_cell_type IS 'Free text description used when converted_cell_type is OTHER. [Sensitivity: NONE]';
COMMENT ON COLUMN location.archived_reason IS 'Why the location was permanently archived rather than merely deactivated. Free text: assume it can name a prisoner. [Sensitivity: PERSONAL]';
COMMENT ON COLUMN location.deactivated_by IS 'DPS username of the person who took the location out of use. [Sensitivity: STAFF]';
COMMENT ON COLUMN location.deactivation_reason_description IS 'Free text expanding on deactivated_reason, and the only detail available when the reason is OTHER. Assume it can name a prisoner - "damaged by" is a common phrasing. [Sensitivity: PERSONAL]';
COMMENT ON COLUMN location.location_type_discriminator IS 'Single-table inheritance discriminator: CELL, RESIDENTIAL, NON_RESIDENTIAL or VIRTUAL. Determines which subclass the row maps to and therefore which columns apply. [Sensitivity: NONE]';
COMMENT ON COLUMN location.status IS 'Lifecycle state of the location - DRAFT, ACTIVE, INACTIVE or ARCHIVED. See LocationStatus in reference-data.csv. [Sensitivity: NONE]';
COMMENT ON COLUMN location.in_cell_sanitation IS 'Whether the cell has its own toilet and washing facilities. Part of the certified specification of a cell. [Sensitivity: NONE]';
COMMENT ON COLUMN location.cell_mark IS 'The number physically painted on the cell door, which can differ from the location code. [Sensitivity: NONE]';
COMMENT ON COLUMN location.residential_structure IS 'Hyphen separated list of the location types making up the path from the top of the prison down to this location, such as WING-LANDING-CELL. Denormalised so the shape of a prison can be read without walking the tree. [Sensitivity: NONE]';
COMMENT ON COLUMN location.internal_movement_allowed IS 'Whether prisoners may move to and from this non-residential location unescorted. [Sensitivity: NONE]';
COMMENT ON COLUMN location.certified_cell IS 'Whether the cell currently appears on the prison''s cell certificate. A cell that is not certified must not be used to hold anyone. [Sensitivity: NONE]';
COMMENT ON COLUMN location.temporarily_off_cell_cert IS 'Whether a certified cell is temporarily suspended from the certificate, for example during refurbishment, without losing its certification. Required for rows where the discriminator is CELL. [Sensitivity: NONE]';
COMMENT ON COLUMN location.hidden_from_list IS 'Whether the location is suppressed from the location lists shown in the UI. Used for locations that exist for data reasons but that staff should not browse. [Sensitivity: NONE]';

COMMENT ON TABLE capacity IS 'The three capacity figures for a single location: how many people it is designed for, how many it is certified for, and how many it can safely hold today.';
COMMENT ON COLUMN capacity.id IS 'Primary key. [Sensitivity: NONE]';
COMMENT ON COLUMN capacity.max_capacity IS 'The most people the location can hold, including overcrowding. [Sensitivity: NONE]';
COMMENT ON COLUMN capacity.working_capacity IS 'How many people the location can hold today, allowing for anything currently out of use. Zero for a location that cannot currently be used. [Sensitivity: NONE]';
COMMENT ON COLUMN capacity.certified_normal_accommodation IS 'Certified normal accommodation (CNA): the uncrowded capacity of the location, as certified. Published by MoJ in the prison population statistics. [Sensitivity: NONE]';

COMMENT ON TABLE location_history IS 'Audit trail of every change to a location: one row per changed attribute, tied to the transaction that changed it.';
COMMENT ON COLUMN location_history.id IS 'Primary key. [Sensitivity: NONE]';
COMMENT ON COLUMN location_history.location_id IS 'The location that changed. [Sensitivity: NONE]';
COMMENT ON COLUMN location_history.attribute_name IS 'Which attribute of the location changed, such as CAPACITY or CODE. See LocationAttribute in reference-data.csv. [Sensitivity: NONE]';
COMMENT ON COLUMN location_history.old_value IS 'The attribute''s value before the change, rendered as text. Carries the sensitivity of whichever attribute changed, so where the attribute was a free-text field this can name a prisoner. [Sensitivity: PERSONAL]';
COMMENT ON COLUMN location_history.new_value IS 'The attribute''s value after the change, rendered as text. Same caveat as old_value. [Sensitivity: PERSONAL]';
COMMENT ON COLUMN location_history.amended_by IS 'DPS username of the person who made the change. [Sensitivity: STAFF]';
COMMENT ON COLUMN location_history.amended_date IS 'When the change was made. [Sensitivity: NONE]';
COMMENT ON COLUMN location_history.linked_transaction_id IS 'The transaction this change belonged to, so all the changes made by one user action can be read together. [Sensitivity: NONE]';

COMMENT ON TABLE linked_transaction IS 'One user action or system job, grouping together every location change it caused. Lets the history be read as "what somebody did" rather than as isolated field changes.';
COMMENT ON COLUMN linked_transaction.id IS 'Primary key, and the transaction identifier exposed in the API. [Sensitivity: NONE]';
COMMENT ON COLUMN linked_transaction.transaction_type IS 'What kind of action this was, such as LOCATION_UPDATE or CAPACITY_CHANGE. Decoded by the constant_transaction_type table. [Sensitivity: NONE]';
COMMENT ON COLUMN linked_transaction.transaction_detail IS 'System generated one line summary of the action, built from a template rather than typed by a user. [Sensitivity: NONE]';
COMMENT ON COLUMN linked_transaction.transaction_invoked_by IS 'DPS username of the person who performed the action, or a system identifier for automated jobs. [Sensitivity: STAFF]';
COMMENT ON COLUMN linked_transaction.tx_start_time IS 'When the transaction started. [Sensitivity: NONE]';
COMMENT ON COLUMN linked_transaction.tx_end_time IS 'When the transaction finished. Null if it is still running or did not complete. [Sensitivity: NONE]';
COMMENT ON COLUMN linked_transaction.prison_id IS 'Prison the transaction applied to, as a NOMIS agency code. [Sensitivity: NONE]';


-- ---------------------------------------------------------------------------------------------------
-- What a location is used for
-- ---------------------------------------------------------------------------------------------------

COMMENT ON TABLE non_residential_usage IS 'What a non-residential location is used for, such as visits or adjudications. A location can have several usages.';
COMMENT ON COLUMN non_residential_usage.id IS 'Primary key. [Sensitivity: NONE]';
COMMENT ON COLUMN non_residential_usage.location_id IS 'The non-residential location this usage applies to. [Sensitivity: NONE]';
COMMENT ON COLUMN non_residential_usage.usage_type IS 'What the location is used for - ADJUDICATION_HEARING, VISIT, PROGRAMMES_ACTIVITIES and so on. Legacy NOMIS classification; service_usage is the modern equivalent. See NonResidentialUsageType in reference-data.csv. [Sensitivity: NONE]';
COMMENT ON COLUMN non_residential_usage."capacity" IS 'How many people the location holds for this particular usage, which can differ from its residential capacity. [Sensitivity: NONE]';
COMMENT ON COLUMN non_residential_usage."sequence" IS 'Sort order when a location has more than one usage. [Sensitivity: NONE]';

COMMENT ON TABLE residential_attribute IS 'Legacy NOMIS attributes of a residential location, retained for the NOMIS sync and for historic reporting. Superseded by specialist_cell and cell_used_for.';
COMMENT ON COLUMN residential_attribute.id IS 'Primary key. [Sensitivity: NONE]';
COMMENT ON COLUMN residential_attribute.location_id IS 'The location the attribute applies to. [Sensitivity: NONE]';
COMMENT ON COLUMN residential_attribute.attribute_type IS 'Which NOMIS attribute domain the value belongs to, such as LOCATION_ATTRIBUTE or SANITATION_FITTINGS. See ResidentialAttributeType in reference-data.csv. [Sensitivity: NONE]';
COMMENT ON COLUMN residential_attribute.attribute_value IS 'The NOMIS attribute value itself. See ResidentialAttributeValue in reference-data.csv. [Sensitivity: NONE]';

COMMENT ON TABLE cell_used_for IS 'What a cell is used for. A cell can serve several purposes, so this is a list rather than a column on location.';
COMMENT ON COLUMN cell_used_for.id IS 'Primary key. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_used_for.location_id IS 'The cell this applies to. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_used_for.used_for IS 'What the cell is used for - STANDARD_ACCOMMODATION, FIRST_NIGHT_CENTRE, DRUG_RECOVERY_UNIT and so on. See UsedForType in reference-data.csv. [Sensitivity: NONE]';

COMMENT ON TABLE specialist_cell IS 'Specialist cell types held against a cell, such as accessible or constant supervision cells. A cell can have several.';
COMMENT ON COLUMN specialist_cell.id IS 'Primary key. [Sensitivity: NONE]';
COMMENT ON COLUMN specialist_cell.location_id IS 'The cell this applies to. [Sensitivity: NONE]';
COMMENT ON COLUMN specialist_cell.specialist_cell_type IS 'The specialist type - ACCESSIBLE_CELL, CONSTANT_SUPERVISION, SAFE_CELL and so on. Some types reduce the cell''s usable capacity. See SpecialistCellType in reference-data.csv. [Sensitivity: NONE]';

COMMENT ON TABLE service_usage IS 'Which DPS services a non-residential location is available to, so each service can offer only the locations relevant to it.';
COMMENT ON COLUMN service_usage.id IS 'Primary key. [Sensitivity: NONE]';
COMMENT ON COLUMN service_usage.location_id IS 'The location this applies to. Deleted with the location. [Sensitivity: NONE]';
COMMENT ON COLUMN service_usage.service_type IS 'The service the location is available to, such as ADJUDICATION_HEARING or VIDEO_LINK. See ServiceType in reference-data.csv. [Sensitivity: NONE]';


-- ---------------------------------------------------------------------------------------------------
-- Prison level configuration
-- ---------------------------------------------------------------------------------------------------

COMMENT ON TABLE prison_configuration IS 'Per-prison settings controlling how this service behaves at that prison. One row per prison, keyed by the prison code itself.';
COMMENT ON COLUMN prison_configuration.prison_id IS 'Primary key: the prison, as a NOMIS agency code. [Sensitivity: NONE]';
COMMENT ON COLUMN prison_configuration.when_updated IS 'When the configuration was last changed. [Sensitivity: NONE]';
COMMENT ON COLUMN prison_configuration.updated_by IS 'DPS username of the person who last changed the configuration. [Sensitivity: STAFF]';
COMMENT ON COLUMN prison_configuration.resi_location_service_active IS 'Whether the prison manages its residential locations in this service rather than in NOMIS. [Sensitivity: NONE]';
COMMENT ON COLUMN prison_configuration.include_segregation_in_roll_count IS 'Whether prisoners in segregation are counted in the prison''s roll count figures. [Sensitivity: NONE]';
COMMENT ON COLUMN prison_configuration.certification_approval_required IS 'Whether changes affecting certified capacity at this prison must go through the approval workflow before taking effect. [Sensitivity: NONE]';
COMMENT ON COLUMN prison_configuration.non_resi_service_active IS 'Whether the prison manages its non-residential locations in this service rather than in NOMIS. [Sensitivity: NONE]';

COMMENT ON TABLE signed_operation_capacity IS 'The signed operational capacity of a prison: the maximum population the governor has signed off as safe to hold. One current row per prison.';
COMMENT ON COLUMN signed_operation_capacity.id IS 'Primary key. [Sensitivity: NONE]';
COMMENT ON COLUMN signed_operation_capacity.prison_id IS 'The prison, as a NOMIS agency code. Unique. [Sensitivity: NONE]';
COMMENT ON COLUMN signed_operation_capacity.signed_operation_capacity IS 'The signed operational capacity figure itself. Published by MoJ in the prison population statistics. [Sensitivity: NONE]';
COMMENT ON COLUMN signed_operation_capacity.when_updated IS 'When the figure was last changed. [Sensitivity: NONE]';
COMMENT ON COLUMN signed_operation_capacity.updated_by IS 'DPS username of the person who last changed the figure. [Sensitivity: STAFF]';

COMMENT ON TABLE prison_notification_mailbox IS 'Email addresses notified about cell certification activity. A row with a null prison_id is the national default for that notification group.';
COMMENT ON COLUMN prison_notification_mailbox.id IS 'Primary key. [Sensitivity: NONE]';
COMMENT ON COLUMN prison_notification_mailbox.prison_id IS 'The prison this mailbox serves, as a NOMIS agency code. Null means it is the default used for any prison without its own entry. [Sensitivity: NONE]';
COMMENT ON COLUMN prison_notification_mailbox.notification_group IS 'Which role the mailbox is notified in - CERT_ADMIN, CERT_VIEWER or CERT_REVIEWER. See NotificationGroup in reference-data.csv. [Sensitivity: NONE]';
COMMENT ON COLUMN prison_notification_mailbox.email_address IS 'Address notified. Usually a shared team mailbox, but can be an individual member of staff, so treat it as staff personal data. [Sensitivity: STAFF]';
COMMENT ON COLUMN prison_notification_mailbox.when_updated IS 'When the mailbox entry was last changed. [Sensitivity: NONE]';
COMMENT ON COLUMN prison_notification_mailbox.updated_by IS 'DPS username of the person who last changed the mailbox entry. [Sensitivity: STAFF]';

COMMENT ON TABLE constant_transaction_type IS 'A copy of the TransactionType enumeration as a table, so reporting tools and the Analytical Platform can decode linked_transaction.transaction_type without hard-coding the list. Kept in sync with the enum by ConstantsTableTest. Deliberately not the target of a foreign key.';
COMMENT ON COLUMN constant_transaction_type.code IS 'Primary key: the transaction type code as stored in linked_transaction.transaction_type. [Sensitivity: NONE]';
COMMENT ON COLUMN constant_transaction_type."sequence" IS 'Display order, matching the order the values are declared in the Kotlin enum. [Sensitivity: NONE]';
COMMENT ON COLUMN constant_transaction_type.description IS 'Human readable description of the transaction type. [Sensitivity: NONE]';


-- ---------------------------------------------------------------------------------------------------
-- Certification approval workflow
--
-- These tables hold changes to the estate that have been *requested* but not yet approved. The capacity
-- figures on them are therefore proposals, not the published position, and are classified
-- OFFICIAL-SENSITIVE rather than NONE: together they describe intended changes to how many people a
-- prison can hold, ahead of any decision or announcement. Once approved the outcome is written to
-- cell_certificate, where the equivalent figures are NONE.
--
-- Columns prefixed current_ hold the value at the time the request was raised, so a reviewer can see
-- what is being changed from as well as to. They are snapshots and will not track later edits.
-- ---------------------------------------------------------------------------------------------------

COMMENT ON TABLE certification_approval_request IS 'A request to change something that affects a prison''s certified capacity, awaiting review. Holds both the proposed values and a snapshot of the current ones, so the request can be assessed without re-reading the live locations.';
COMMENT ON COLUMN certification_approval_request.id IS 'Primary key. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.prison_id IS 'Prison the request applies to, as a NOMIS agency code. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.location_id IS 'The location the request is about. Null for prison-wide requests such as a signed operational capacity change. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.location_key IS 'The location''s key ({prisonId}-{pathHierarchy}) captured when the request was raised, so the request stays readable if the location is later renamed or removed. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.status IS 'Where the request has got to - PENDING, APPROVED, REJECTED or WITHDRAWN. See ApprovalRequestStatus in reference-data.csv. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.requested_by IS 'DPS username of the person who raised the request. [Sensitivity: STAFF]';
COMMENT ON COLUMN certification_approval_request.requested_date IS 'When the request was raised. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.approved_or_rejected_by IS 'DPS username of the person who approved or rejected the request. Null while it is still pending. [Sensitivity: STAFF]';
COMMENT ON COLUMN certification_approval_request.approved_or_rejected_date IS 'When the request was approved or rejected. Null while it is still pending. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.comments IS 'Free text left by the approver explaining their decision. Assume it can name a prisoner. [Sensitivity: PERSONAL]';
COMMENT ON COLUMN certification_approval_request.certified_normal_accommodation_change IS 'Net change to the prison''s certified normal accommodation if this request is approved. A proposal, not the published figure. [Sensitivity: OFFICIAL-SENSITIVE]';
COMMENT ON COLUMN certification_approval_request.working_capacity_change IS 'Net change to working capacity if this request is approved. [Sensitivity: OFFICIAL-SENSITIVE]';
COMMENT ON COLUMN certification_approval_request.max_capacity_change IS 'Net change to maximum capacity if this request is approved. [Sensitivity: OFFICIAL-SENSITIVE]';
COMMENT ON COLUMN certification_approval_request.approval_type IS 'What kind of change is being requested - DEACTIVATION, CAPACITY_CHANGE, SIGNED_OP_CAP and so on. Determines which of the proposed value columns below are populated. See ApprovalType in reference-data.csv. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.signed_operation_capacity_change IS 'Net change to the prison''s signed operational capacity if this request is approved. [Sensitivity: OFFICIAL-SENSITIVE]';
COMMENT ON COLUMN certification_approval_request.signed_operation_capacity_id IS 'The signed_operation_capacity row this request would update. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.reason_for_change IS 'Free text from the requester explaining why the change is needed. Assume it can name a prisoner. [Sensitivity: PERSONAL]';
COMMENT ON COLUMN certification_approval_request.current_signed_operation_capacity IS 'The prison''s signed operational capacity when the request was raised, as a snapshot for comparison. Already published, so not sensitive in itself. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.cell_mark IS 'Proposed new cell door number. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.deactivated_reason IS 'Proposed reason for taking the location out of use. See DeactivatedReason in reference-data.csv. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.deactivation_reason_description IS 'Free text expanding on the proposed deactivation reason. Assume it can name a prisoner. [Sensitivity: PERSONAL]';
COMMENT ON COLUMN certification_approval_request.proposed_reactivation_date IS 'Date the location is expected to come back into use, if the deactivation is approved. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.planet_fm_reference IS 'Planet FM job reference for the maintenance work behind the request. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.in_cell_sanitation IS 'Proposed in-cell sanitation setting. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.current_cell_mark IS 'The cell door number when the request was raised, as a snapshot for comparison. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.current_in_cell_sanitation IS 'The in-cell sanitation setting when the request was raised, as a snapshot for comparison. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.max_capacity IS 'Proposed maximum capacity for the location. [Sensitivity: OFFICIAL-SENSITIVE]';
COMMENT ON COLUMN certification_approval_request.working_capacity IS 'Proposed working capacity for the location. [Sensitivity: OFFICIAL-SENSITIVE]';
COMMENT ON COLUMN certification_approval_request.certified_normal_accommodation IS 'Proposed certified normal accommodation for the location. [Sensitivity: OFFICIAL-SENSITIVE]';
COMMENT ON COLUMN certification_approval_request.pending_specialist_cell_types IS 'Proposed specialist cell types, as a comma separated list. Denormalised because the request is a snapshot rather than a live relationship. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.converted_cell_type IS 'Proposed non-residential use for a cell being converted. See ConvertedCellType in reference-data.csv. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.other_converted_cell_type IS 'Free text description used when the proposed converted_cell_type is OTHER. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.accommodation_type IS 'Proposed accommodation type for the location. See AccommodationType in reference-data.csv. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.used_for_types IS 'Proposed list of what the cell is used for, comma separated. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.current_accommodation_types IS 'The accommodation types when the request was raised, as a snapshot for comparison. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.current_used_for_types IS 'What the cell was used for when the request was raised, as a snapshot for comparison. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.top_level_accommodation_types IS 'Accommodation types of the top level location above this one, so a reviewer can see the request in the context of the wing it sits in. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request.top_level_used_for_types IS 'What the top level location above this one is used for, for the same reason. [Sensitivity: NONE]';

COMMENT ON TABLE certification_approval_request_location IS 'The locations covered by an approval request, held as a self-contained tree that is copied from the live locations when the request is raised. Kept separate from the location table so a request shows what was asked for even if the estate changes afterwards.';
COMMENT ON COLUMN certification_approval_request_location.id IS 'Primary key. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request_location.certification_approval_request_id IS 'The approval request this location belongs to. Deleted with the request. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request_location.location_code IS 'The location''s own code within its parent, copied from the live location. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request_location.cell_mark IS 'Proposed number on the cell door. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request_location.local_name IS 'The name the prison uses for this location. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request_location.path_hierarchy IS 'Full path of the location within the prison, copied when the request was raised. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request_location."level" IS 'Depth of this location in the request''s tree, with the top level location at the lowest number. Lets the tree be rendered without recursion. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request_location.certified_normal_accommodation IS 'Proposed certified normal accommodation for this location. [Sensitivity: OFFICIAL-SENSITIVE]';
COMMENT ON COLUMN certification_approval_request_location.working_capacity IS 'Proposed working capacity for this location. [Sensitivity: OFFICIAL-SENSITIVE]';
COMMENT ON COLUMN certification_approval_request_location.max_capacity IS 'Proposed maximum capacity for this location. [Sensitivity: OFFICIAL-SENSITIVE]';
COMMENT ON COLUMN certification_approval_request_location.in_cell_sanitation IS 'Proposed in-cell sanitation setting for this location. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request_location.location_type IS 'What kind of location this is. See LocationType in reference-data.csv. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request_location.specialist_cell_types IS 'Proposed specialist cell types, comma separated. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request_location.converted_cell_type IS 'Proposed non-residential use for a cell being converted. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request_location.parent_location_id IS 'The location above this one within the request''s own tree, not the live location tree. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request_location.used_for_types IS 'Proposed list of what the cell is used for, comma separated. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request_location.accommodation_types IS 'Proposed accommodation types, comma separated. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request_location.current_working_capacity IS 'Working capacity when the request was raised, as a snapshot for comparison. [Sensitivity: OFFICIAL-SENSITIVE]';
COMMENT ON COLUMN certification_approval_request_location.current_max_capacity IS 'Maximum capacity when the request was raised, as a snapshot for comparison. [Sensitivity: OFFICIAL-SENSITIVE]';
COMMENT ON COLUMN certification_approval_request_location.current_certified_normal_accommodation IS 'Certified normal accommodation when the request was raised, as a snapshot for comparison. [Sensitivity: OFFICIAL-SENSITIVE]';
COMMENT ON COLUMN certification_approval_request_location.reactivate_this_location IS 'Whether this particular location should be brought back into use if the request is approved. A request can cover a tree in which only some locations are reactivated. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request_location.current_specialist_cell_types IS 'Specialist cell types when the request was raised, as a snapshot for comparison. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request_location.current_cell_mark IS 'The cell door number when the request was raised, as a snapshot for comparison. [Sensitivity: NONE]';
COMMENT ON COLUMN certification_approval_request_location.current_in_cell_sanitation IS 'In-cell sanitation setting when the request was raised, as a snapshot for comparison. [Sensitivity: NONE]';


-- ---------------------------------------------------------------------------------------------------
-- Cell certificates - the approved outcome
--
-- A cell certificate is the signed, published record of what a prison is certified to hold. The capacity
-- figures here are the approved position rather than a proposal, so they are NONE where the equivalent
-- columns on certification_approval_request are OFFICIAL-SENSITIVE.
-- ---------------------------------------------------------------------------------------------------

COMMENT ON TABLE cell_certificate IS 'A point-in-time certificate recording what a prison was certified to hold, with the full location tree as it stood when the certificate was issued. A new certificate is issued each time an approval changes certified capacity; only one is current per prison.';
COMMENT ON COLUMN cell_certificate.id IS 'Primary key. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate.prison_id IS 'The prison this certificate covers, as a NOMIS agency code. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate.approved_by IS 'DPS username of the person who approved the certificate. [Sensitivity: STAFF]';
COMMENT ON COLUMN cell_certificate.approved_date IS 'When the certificate was approved. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate.certification_approval_request_id IS 'The approval request that produced this certificate. Null for certificates created by the initial prison baseline rather than by a request. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate.total_working_capacity IS 'Total working capacity across the prison at the point of certification. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate.total_max_capacity IS 'Total maximum capacity across the prison at the point of certification. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate.total_certified_normal_accommodation IS 'Total certified normal accommodation across the prison at the point of certification. Published by MoJ in the prison population statistics. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate."current" IS 'Whether this is the prison''s current certificate. Exactly one row per prison should be true; the rest are superseded and kept for history. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate.signed_operation_capacity IS 'The prison''s signed operational capacity at the point of certification. [Sensitivity: NONE]';

COMMENT ON TABLE cell_certificate_location IS 'The location tree as recorded on a cell certificate: a frozen copy taken when the certificate was issued, so the certificate remains an accurate record even after the live locations change.';
COMMENT ON COLUMN cell_certificate_location.id IS 'Primary key. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_location.cell_certificate_id IS 'The certificate this location belongs to. Deleted with the certificate. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_location.location_code IS 'The location''s own code within its parent, as certified. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_location.path_hierarchy IS 'Full path of the location within the prison, as certified. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_location.certified_normal_accommodation IS 'Certified normal accommodation for this location, as certified. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_location.working_capacity IS 'Working capacity for this location, as certified. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_location.max_capacity IS 'Maximum capacity for this location, as certified. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_location.in_cell_sanitation IS 'Whether the cell had its own toilet and washing facilities, as certified. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_location.location_type IS 'What kind of location this is. See LocationType in reference-data.csv. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_location.specialist_cell_types IS 'Specialist cell types held against the location, comma separated, as certified. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_location.cell_mark IS 'The number on the cell door, as certified. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_location."level" IS 'Depth of this location in the certificate''s tree, with the top level location at the lowest number. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_location.local_name IS 'The name the prison used for this location, as certified. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_location.parent_location_id IS 'The location above this one within the certificate''s own tree, not the live location tree. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_location.converted_cell_type IS 'What a former cell was being used as, as certified. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_location.used_for_types IS 'What the cell was used for, comma separated, as certified. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_location.accommodation_types IS 'Accommodation types for the location, comma separated, as certified. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_location.other_converted_cell_type IS 'Free text description used when the certified converted_cell_type was OTHER. [Sensitivity: NONE]';


-- ---------------------------------------------------------------------------------------------------
-- Bulk certificate upload
--
-- Capacity figures here are proposed values being imported and reconciled against what the service
-- already holds, so they follow the approval-request classification rather than the certificate one
-- until the upload has been approved.
-- ---------------------------------------------------------------------------------------------------

COMMENT ON TABLE cell_certificate_upload IS 'One run of the bulk import that seeds or corrects a prison''s cell certificate from a spreadsheet, with counts of how the run went.';
COMMENT ON COLUMN cell_certificate_upload.id IS 'Primary key. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_upload.prison_id IS 'The prison being imported, as a NOMIS agency code. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_upload.status IS 'Where the run has got to - PENDING, STARTED or FINISHED. See CellCertificateUploadStatus in reference-data.csv. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_upload.requested_by IS 'DPS username of the person who started the import. [Sensitivity: STAFF]';
COMMENT ON COLUMN cell_certificate_upload.requested_date IS 'When the import was requested. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_upload.start_time IS 'When processing actually began. Null while the run is still queued. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_upload.end_time IS 'When processing finished. Null while the run is still going. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_upload.total_records IS 'How many rows the uploaded file contained. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_upload.processed_records IS 'How many rows were applied successfully. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_upload.skipped_records IS 'How many rows were deliberately skipped, typically because they matched what the service already held. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_upload.failed_records IS 'How many rows could not be applied. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_upload.reason_for_change IS 'Free text from the requester explaining why the import was run. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_upload.cell_certificate_id IS 'The certificate produced by this run, once it has completed. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_upload.discrepancy_records IS 'How many rows differed from what the service already held, and so needed review rather than straight application. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_upload.certification_approval_request_id IS 'The approval request raised off the back of this import, where the discrepancies needed approving. [Sensitivity: NONE]';

COMMENT ON TABLE cell_certificate_upload_location IS 'One row of a bulk certificate import: the values being imported for a location, the values the service already held, and what happened when the two were reconciled.';
COMMENT ON COLUMN cell_certificate_upload_location.id IS 'Primary key. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_upload_location.cell_certificate_upload_id IS 'The import run this row belongs to. Deleted with the run. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_upload_location.location_key IS 'The location this row is about, as {prisonId}-{pathHierarchy}. Matched by key rather than by id because the spreadsheet has no ids. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_upload_location.max_capacity IS 'Maximum capacity given in the uploaded file. A proposed value until the import is approved. [Sensitivity: OFFICIAL-SENSITIVE]';
COMMENT ON COLUMN cell_certificate_upload_location.working_capacity IS 'Working capacity given in the uploaded file. [Sensitivity: OFFICIAL-SENSITIVE]';
COMMENT ON COLUMN cell_certificate_upload_location.certified_normal_accommodation IS 'Certified normal accommodation given in the uploaded file. [Sensitivity: OFFICIAL-SENSITIVE]';
COMMENT ON COLUMN cell_certificate_upload_location.cell_mark IS 'Cell door number given in the uploaded file. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_upload_location.in_cell_sanitation IS 'In-cell sanitation setting given in the uploaded file. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_upload_location.status IS 'What happened to this row - PENDING, PROCESSED, SKIPPED or FAILED. See CellCertificateUploadLocationStatus in reference-data.csv. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_upload_location.previous_max_capacity IS 'Maximum capacity the service held for this location before the import, for comparison. [Sensitivity: OFFICIAL-SENSITIVE]';
COMMENT ON COLUMN cell_certificate_upload_location.previous_working_capacity IS 'Working capacity the service held before the import, for comparison. [Sensitivity: OFFICIAL-SENSITIVE]';
COMMENT ON COLUMN cell_certificate_upload_location.previous_certified_normal_accommodation IS 'Certified normal accommodation the service held before the import, for comparison. [Sensitivity: OFFICIAL-SENSITIVE]';
COMMENT ON COLUMN cell_certificate_upload_location.previous_cell_mark IS 'Cell door number the service held before the import, for comparison. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_upload_location.previous_in_cell_sanitation IS 'In-cell sanitation setting the service held before the import, for comparison. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_upload_location.message IS 'System generated explanation of why the row was skipped or failed. Not typed by a user. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_upload_location.processed_date IS 'When this row was processed. Null while the row is still pending. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_certificate_upload_location.working_capacity_mismatch IS 'Whether the uploaded working capacity differed from what the service already held, flagging the row for review. [Sensitivity: OFFICIAL-SENSITIVE]';
COMMENT ON COLUMN cell_certificate_upload_location.max_capacity_mismatch IS 'Whether the uploaded maximum capacity differed from what the service already held. [Sensitivity: OFFICIAL-SENSITIVE]';
COMMENT ON COLUMN cell_certificate_upload_location.certified_normal_accommodation_mismatch IS 'Whether the uploaded certified normal accommodation differed from what the service already held. [Sensitivity: OFFICIAL-SENSITIVE]';
COMMENT ON COLUMN cell_certificate_upload_location.applied_max_capacity IS 'The maximum capacity actually applied to the location, which can differ from the uploaded value where the import had to reconcile a mismatch. [Sensitivity: OFFICIAL-SENSITIVE]';


-- ---------------------------------------------------------------------------------------------------
-- Migration leftover
-- ---------------------------------------------------------------------------------------------------

-- certification_backup is the one table here that is not part of the running application: V1_74 created
-- it with CREATE TABLE AS SELECT as a safety net before certification data moved onto location, and
-- nothing has read or written it since. Because no code depends on it, it can be - and in at least one
-- environment has been - dropped by hand, so it is present in a freshly migrated database but absent
-- elsewhere. An unguarded COMMENT ON then aborts this migration and, with it, application startup.
-- Comment it only where it still exists.
DO $certification_backup$
BEGIN
  IF to_regclass('certification_backup') IS NULL THEN
    RAISE NOTICE 'certification_backup is not present in this database; skipping its comments';
    RETURN;
  END IF;

  EXECUTE $c$COMMENT ON TABLE certification_backup IS 'One-off backup taken by migration V1_74 (CREATE TABLE AS SELECT) before certification data moved onto the location table. Not written to by the application and not read by anything - a candidate for removal in a later migration. Absent from any environment where it has already been dropped by hand.'$c$;
  EXECUTE $c$COMMENT ON COLUMN certification_backup.location_id IS 'The location the backed up certification row belonged to. [Sensitivity: NONE]'$c$;
  EXECUTE $c$COMMENT ON COLUMN certification_backup.certificate_id IS 'Primary key of the row in the old certification table, which has since been dropped. [Sensitivity: NONE]'$c$;
  EXECUTE $c$COMMENT ON COLUMN certification_backup.certified IS 'Whether the location was certified, as at migration V1_74. [Sensitivity: NONE]'$c$;
  EXECUTE $c$COMMENT ON COLUMN certification_backup.certified_normal_accommodation IS 'Certified normal accommodation for the location, as at migration V1_74. [Sensitivity: NONE]'$c$;
END
$certification_backup$;
